#Include <Paths>
#Include <Links>
#Include <Char>
#Include <Base>
#Include <Global>
#Include <Press>
#Include <Sort>
#Include <Win>
#Include <Eval>
#Include <Json>
#Include <String-full>
#Include <Tools>
#Include <App>
#Include <Other>
#Include <Script>
#Include <Gui>
#Include <String>
#Include <print>
#Include <Win-full>
#Include <Info>
#Include <ClipSend>
#Include <Cmd>
#Include <Get>
#Include <CGdip>