#Include C:\Programming\lib-v2\
#Include Paths.ahk
#Include Links.ahk
#Include Char.ahk
#Include Base.ahk
#Include Global.ahk
#Include Press.ahk
#Include Sort.ahk
#Include Win.ahk
#Include Eval.ahk
#Include Json.ahk
#Include String-full.ahk
#Include Tools.ahk
#Include App.ahk
#Include Other.ahk
#Include Script.ahk
#Include Gui.ahk
#Include String.ahk
#Include print.ahk
#Include Win-full.ahk
#Include Info.ahk
#Include ClipSend.ahk
#Include Cmd.ahk