#Include <App\Browser>
#Include <App\Spotify>
#Include <App\VK>
#Include <App\Youtube>
#Include <App\Telegram>
#Include <App\Discord>
#Include <App\VsCode>
#Include <App\Terminal>
#Include <App\Git>
#Include <App\GitHub>
#Include <App\Shows>
#Include <App\Video>
#Include <App\Explorer>
#Include <App\Davinci>
#Include <App\Screenshot>
#Include <App\Player>
#Include <App\Gimp>
#Include <App\LosslessCut>
#Include <App\OBS>
#Include <App\Autohotkey>