#Include <Scr\App\Discord>
#Include <Scr\App\Spotify>
#Include <Scr\App\YouTube>
#Include <Scr\App\Browser>
#Include <Scr\App\VK>
#Include <Scr\App\VsCode>
#Include <Scr\App\Player>
#Include <Scr\App\Davinci>
#Include <Scr\App\Autohotkey>
