#Include <App\Explorer>
#Include <App\OBS>
#Include <App\Terminal>
#Include <App\Spotify>
#Include <App\Discord>
#Include <App\Browser>
#Include <App\Telegram>
#Include <App\VsCode>
#Include <App\VPN>

GroupAdd("Main", VsCode.winTitle)
GroupAdd("Main", Spotify.exeTitle)
GroupAdd("Main", Discord.winTitle)
GroupAdd("Main", Browser.winTitle)
GroupAdd("Main", Telegram.winTitle)
GroupAdd("Main", Terminal.winTitle)
GroupAdd("Main", Explorer.exeTitle)
GroupAdd("Main", OBS.winTitle)
GroupAdd("Main", VPN.winTitle)